/* ============================================================
   Werbemittel-Katalog — AUTOMATISCH ERZEUGT aus
   ClayTec-Werbemittelbestellliste-06-2026.xlsx (Stand 06/2026).
   Bei neuer Bestellliste neu generieren lassen, nicht von Hand pflegen.
   ============================================================ */
var CRM = window.CRM || {};
window.CRM = CRM;

CRM.WERBEMITTEL = [
  {"nr": "60.444", "name": "ClayTec Produktkatalog", "desc": "4-farbig, DIN A4, 40 Seiten", "ve": 10, "kat": "Broschüren, Arbeitsblätter und Leitfäden"},
  {"nr": "60.046", "name": "ClayTec Info Booklet", "desc": "4-farbig, DIN A5, 16 Seiten", "ve": 10, "kat": "Broschüren, Arbeitsblätter und Leitfäden"},
  {"nr": "60.669", "name": "ClayTec Infomappe", "desc": "", "ve": 1, "kat": "Broschüren, Arbeitsblätter und Leitfäden"},
  {"nr": "60.391", "name": "Lehm-Holzbau Broschüre", "desc": "4-farbig, DIN A4 quer, 28 Seiten", "ve": 10, "kat": "Broschüren, Arbeitsblätter und Leitfäden"},
  {"nr": "60.400", "name": "YOSIMA Broschüre", "desc": "4-farbig, DIN A4 quer, 32 Seiten", "ve": 10, "kat": "Broschüren, Arbeitsblätter und Leitfäden"},
  {"nr": "60.390", "name": "Fachwerk Broschüre", "desc": "4-farbig, DIN A4 quer, 32 Seiten", "ve": 10, "kat": "Broschüren, Arbeitsblätter und Leitfäden"},
  {"nr": "60.281", "name": "ClayFix  Farbtonübersicht", "desc": "8 Kartonseiten, 29,7 x 13,0 cm, Wire-O-Bindung", "ve": 1, "kat": "Broschüren, Arbeitsblätter und Leitfäden"},
  {"nr": "60.043", "name": "ClayTec - YouTube Flyer", "desc": "DIN lang, 4 farbig, 4 seitig", "ve": 10, "kat": "Broschüren, Arbeitsblätter und Leitfäden"},
  {"nr": "60.125", "name": "Arbeitsblatt Feine Oberflächen", "desc": "4-farbig, DIN A4, 16 Seiten", "ve": 10, "kat": "Broschüren, Arbeitsblätter und Leitfäden"},
  {"nr": "60.126", "name": "Arbeitsblatt Lehmputze", "desc": "4-farbig, DIN A4, 12 Seiten", "ve": 10, "kat": "Broschüren, Arbeitsblätter und Leitfäden"},
  {"nr": "60.123", "name": "Leitfaden / Arbeitsblatt Trockenbau", "desc": "4-farbig, DIN A4, 60 Seiten", "ve": 10, "kat": "Broschüren, Arbeitsblätter und Leitfäden"},
  {"nr": "60.127", "name": "Arbeitsblatt Fachwerk", "desc": "4-farbig, DIN A4, 16 Seiten", "ve": 10, "kat": "Broschüren, Arbeitsblätter und Leitfäden"},
  {"nr": "60.128", "name": "Arbeitsblatt Innendämmung", "desc": "4-farbig, DIN A4, 20 Seiten", "ve": 10, "kat": "Broschüren, Arbeitsblätter und Leitfäden"},
  {"nr": "60.047", "name": "Plakat „Sanierung“ für Innenanbringung", "desc": "60 x 115 cm, gerollt", "ve": 1, "kat": "Point-of-Sale-Gestaltung"},
  {"nr": "60.048", "name": "Plakat „Lehmputze“ für Innenanbringung", "desc": "60 x 115 cm, gerollt", "ve": 1, "kat": "Point-of-Sale-Gestaltung"},
  {"nr": "60.049", "name": "Plakat „Trockenbau“ für Innenanbringung", "desc": "60 x 115 cm, gerollt", "ve": 1, "kat": "Point-of-Sale-Gestaltung"},
  {"nr": "70.492", "name": "Versandrolle braun 60 x 640 mm für Plakatversand (max. 5 Plakate)", "desc": "", "ve": 1, "kat": "Point-of-Sale-Gestaltung"},
  {"nr": "60.041", "name": "ClayTec Beach Flag DE", "desc": "37 x 156 cm inkl. Standfuß für den Innenbereich", "ve": 1, "kat": "Point-of-Sale-Gestaltung"},
  {"nr": "60.042", "name": "ClayTec Palettenhusse", "desc": "120 x 80 x 43 cm (für 3 gestapelte Paletten)", "ve": 1, "kat": "Point-of-Sale-Gestaltung"},
  {"nr": "60.005", "name": "ClayTec Roll-up", "desc": "85 x 225 cm", "ve": 1, "kat": "Point-of-Sale-Gestaltung"},
  {"nr": "60.551", "name": "Musteraufsteller Trockenbau inkl. Kopfteil, Ablagefläche und neunteiligem Musterset", "desc": "78 x 195 x 45 cm), zzgl. Transportbox", "ve": 1, "kat": "Point-of-Sale-Gestaltung"},
  {"nr": "60.542", "name": "Musteraufsteller Lehmputze inkl. Kopfteil, Ablagefläche und vierteiligem Musterset", "desc": "78 x 195 x 45 cm), zzgl. Transportbox", "ve": 1, "kat": "Point-of-Sale-Gestaltung"},
  {"nr": "60.544", "name": "Musteraufsteller Lehm-Finish inkl. Kopfteil, Ablagefläche und sechzehnteiligem Musterset", "desc": "78 x 195 x 45 cm), zzgl. Transportbox", "ve": 1, "kat": "Point-of-Sale-Gestaltung"},
  {"nr": "60.550", "name": "Transportbox für 1 bis 3 Musteraufsteller", "desc": "", "ve": 1, "kat": "Point-of-Sale-Gestaltung"},
  {"nr": "60.031", "name": "ClayTec Logo-Aufkleber, Folie", "desc": "2-farbig, 12 x 4 cm", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.050", "name": "Schreibblock", "desc": "DIN A4, rotes Deckblatt, weiß, liniert, 25 Blatt", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.057", "name": "Kugelschreiber", "desc": "D 13 mm, Qualitätsmine", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.055", "name": "Holz-Meterstab", "desc": "2 m, Farbe Natur", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.056", "name": "Zimmererbleistift", "desc": "Querschnitt oval, Farbe Natur", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.058", "name": "Pack-Klebeband", "desc": "B 50 mm, L 50 m, 100% Papier", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.640", "name": "Kartonmesser", "desc": "20 mm Klinge, feststell- und abbrechbar", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.630", "name": "Kaffeetasse (Pott)", "desc": "0,3 l, Emaille weiß", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.600", "name": "Baseball-Kappe", "desc": "Baumwolle, mit Schirm", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.010/M", "name": "T-Shirt, Armlänge 1/4", "desc": "Größe M, Basic-Wear stone, Logo Vorder- und Rückseite", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.010/L", "name": "T-Shirt, Armlänge 1/4", "desc": "Größe L, Basic-Wear stone, Logo Vorder- und Rückseite", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.010/XL", "name": "T-Shirt, Armlänge 1/4", "desc": "Größe XL, Basic-Wear stone, Logo Vorder- und Rückseite", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.010/XXL", "name": "T-Shirt, Armlänge 1/4", "desc": "Größe XXL, Basic-Wear stone, Logo Vorder- und Rückseite", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.010/XXXL", "name": "T-Shirt, Armlänge 1/4", "desc": "Größe XXXL, Basic-Wear stone, Logo Vorder- und Rückseite", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.011/M", "name": "Sweat-Shirt, Armlänge 1/1", "desc": "Größe M, Basic-Wear stone, Logo Vorder- und Rückseite", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.011/L", "name": "Sweat-Shirt, Armlänge 1/1", "desc": "Größe L, Basic-Wear stone, Logo Vorder- und Rückseite", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.011/XL", "name": "Sweat-Shirt, Armlänge 1/1", "desc": "Größe XL, Basic-Wear stone, Logo Vorder- und Rückseite", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.011/XXL", "name": "Sweat-Shirt, Armlänge 1/1", "desc": "Größe XXL, Basic-Wear stone, Logo Vorder- und Rückseite", "ve": 1, "kat": "Werbemittel und Merchandise"},
  {"nr": "60.401", "name": "YOSIMA Farbfächer DE/EN", "desc": "24 x 6 cm · 36 Farbblätter mit modifiziertem Originalmaterial, 25 Textblätter", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60.402", "name": "YOSIMA Mustermappe, DE/EN", "desc": "220 x 310 mm, D 26 mm · 12 Farb- und Strukturmuster 89 x 80 mm", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60.460", "name": "Flächenmuster gerieben und glatt, YOSIMA Lehm-Designputz Classic", "desc": "12 Stück 14 x 14 cm, im Karton · 1.Lehmfarbe verarbeitungsfertig auf Lehm-Oberputz fein 06 gerieben · 2.Lehmfarbe verarbeitungsfertig auf Lehmfüll- und Flächenspachtel · 3.YOSIMA Lehm-Farbspachtel WE0 · 4. YOSIMA Lehm-Designputz WEISS · 5. YOSIMA Lehm-Designputz Alt-Weiss · 6. YOSIMA Lehm-Designputz Kolumba-Grau · 7. YOSIMA Lehm-Designputz Lilien-Weiss · 8. YOSIMA Lehm-Designputz Alma-Weiss · 9. YOSIMA Lehm-Designputz Magnolien-Weiss · 10. YOSIMA Lehm-Designputz Edel-Weiss · 11. YOSIMA Lehm-Designputz Seiden-Weiss · 12. YOSIMA Lehm-Designputz Woll-Weiss", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60.461", "name": "Flächenmuster ClayFix Lehm-Anstrich und YOSIMA Lehm-Designputz WEISS mit Strukturzuschlägen", "desc": "10 Stück 14 x 14 cm, im Karton · 1. ClayFix WE0 ohne Korn · 2. ClayFix WE0 ohne Feinkorn · 3. ClayFix WE0 ohne Grobkorn · 4. YOSIMA Lehm-Designputz WEISS · 5. YOSIMA Lehm-Designputz WEISS Stroh · 6. YOSIMA Lehm-Designputz WEISS Japan · 7. YOSIMA Lehm-Designputz WEISS Herbs · 8. YOSIMA Lehm-Designputz WEISS Red Stone · 9. YOSIMA Lehm-Designputz WEISS Pearl · 10. YOSIMA Lehm-Designputz WEISS Flash", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60.465", "name": "Flächenmuster YOSIMA Lehm-Designputz Grundfarbtöne und Farbraumtöne 1.2", "desc": "12 Stück 14 x 14 cm, im Karton · 1. YOSIMA Lehm-Designputz rot RO 0 · 2. YOSIMA Lehm-Designputz gelb GE 0 · 3. YOSIMA Lehm-Designputz grün GR 0 · 4. YOSIMA Lehm-Designputz braun BR 0 · 5. YOSIMA Lehm-Designputz schwarz SC 0 · 6. YOSIMA Lehm-Designputz ROGE 1.2 (Farbraum Indisch-Rot) · 7. YOSIMA Lehm-Designputz SCBR 1.2 (Farbraum Umbra-Natur) · 8. YOSIMA Lehm-Designputz SCGE 1.2 (Farbraum Sahara-Beige) · 9. YOSIMA Lehm-Designputz BRGE 1.2 (Farbraum Gold-Ocker) · 10. YOSIMA Lehm-Designputz GRGE 1.2 (Farbraum Schilf-Gelb) · 11. YOSIMA Lehm-Designputz SCGR 1.2 (Farbraum Jade-Grün) · 12. YOSIMA Lehm-Designputz SCRO 1.2 (Farbraum Siena-Braun)", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60.480", "name": "Flächenmuster, Lehm-Farbputz grob", "desc": "6 Stück, 14 x 14 cm, im Karton · Je 1 Stück: HELL, GRAU, ROT, GRÜN, GELB, BEIGE", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60.067", "name": "Produktmuster Lehmplatte schwer D16 (Art. Nr. 09.015)", "desc": "21 x 14 x 1,6 cm, im Karton", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60.068", "name": "Produktmuster ClayTec HFA dünn (Art.-Nr. 09.009)", "desc": "21 x 14 x 0,8 cm, im Karton", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60.089", "name": "Produktmuster ClayTec HFA maxi  (Art.-Nr. 09.226)", "desc": "21 x 14 x 2,5 cm, im Karton", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60.065", "name": "Produktmuster ClayTec HFD Innendämmplatte D60 (Art. Nr. 09.465)", "desc": "21 x 14 x 6,0 cm, im Karton", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60.081", "name": "Produktmuster Lehm-Trockenputzplatte D16 (Art.-Nr. 09.010)", "desc": "21 x 14 x 1,6 cm, im Karton", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60071", "name": "Produktmuster ClayTec Lehmbauplatte leicht 22mm  (Art.-Nr. 09.016)", "desc": "21 x 14 x 2,2 cm im Karton", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60072", "name": "Produktmuster ClayTec Lehmbauplatte leicht 14mm  (Art.-Nr. 09.017)", "desc": "21 x 14 x 2,2 cm im Karton", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60.061", "name": "Produktmuster Lehmplatte schwer D22 (Art.-Nr. 09.014)", "desc": "21 x 14 x 2,2 cm, im Karton · mit Beschichtung: Lehmklebe- und Armiermörtel mit Glasgewebe 112, Anstrich Lehmfarbe verarbeitungsfertig", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60.070", "name": "Produktmuster ClayTec Lehmbauplatte D22 solar (Art. Nr. 09.100)", "desc": "21 x 14 x 2,5 cm, im Karton · mit Beschichtung: Lehmklebe- und Armiermörtel mit Glasgewebe 112, Anstrich Lehmfarbe verarbeitungsfertig", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60.062", "name": "Produktmuster ClayTec HFA N+F D20 (Art.-Nr. 09.221)", "desc": "21 x 14 x 2,5 cm, im Karton · mit Beschichtung: Lehmklebe- und Armiermörtel mit Glasgewebe 112, Anstrich Lehmfarbe verarbeitungsfertig", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60.063", "name": "Produktmuster ClayTec HFA Maxi  (Art.-Nr. 09.226)", "desc": "21 x 14 x 2,5 cm, im Karton · mit Beschichtung: Lehmklebe- und Armiermörtel mit Glasgewebe 112, Anstrich Lehmfarbe verarbeitungsfertig", "ve": 1, "kat": "Flächenmuster, Handmuster"},
  {"nr": "60.111", "name": "Materialprobe Lehm-Unterputz (Art.-Nr. 05.001, 05.002, 10.110)", "desc": "3 kg-Beutel", "ve": 1, "kat": "Materialproben"},
  {"nr": "60.112", "name": "Materialpr. Lehm-Oberputz grob (Art.-Nr. 05.010, 05.012, 10.112)", "desc": "3 kg-Beutel", "ve": 1, "kat": "Materialproben"},
  {"nr": "60.114", "name": "Materialprobe Lehm-Oberputz fein 06 (Art.-Nr. 05.113, 10.113)", "desc": "2 kg-Beutel", "ve": 1, "kat": "Materialproben"},
  {"nr": "60.115", "name": "Materialprobe Lehmputz Mineral 20 - trocken (Art.-Nr. 10.130, 05.032)", "desc": "3 kg-Beutel", "ve": 1, "kat": "Materialproben"},
  {"nr": "60.118", "name": "Materialprobe Lehmputz SanReMo (Art.-Nr. 05.810, 10.810)", "desc": "2 kg-Beutel", "ve": 1, "kat": "Materialproben"},
  {"nr": "60.116", "name": "Materialprobe Lehmklebe- und Armierungsmörtel (Art.-Nr. 13.555)", "desc": "2 kg-Beutel", "ve": 1, "kat": "Materialproben"},
  {"nr": "60.129", "name": "Materialprobe Lehm-Dünnbettmörtel (Art.Nr.: 10.150),", "desc": "2 kg-Beutel", "ve": 1, "kat": "Materialproben"},
  {"nr": "60.121", "name": "Materialprobe Lehmfüll- und Flächenspachtel natur-hell (Art.-Nr. 13.531, 13.530)", "desc": "1 kg-Beutel", "ve": 1, "kat": "Materialproben"},
  {"nr": "60.210", "name": "Materialprobe Lehm-Farbputz grob HELL (Art.Nr.: 10.210)", "desc": "2 kg-Beutel", "ve": 1, "kat": "Materialproben"},
  {"nr": "60.220", "name": "Materialprobe Lehm-Farbputz grob GRAU (Art.Nr.: 10.220)", "desc": "2 kg-Beutel", "ve": 1, "kat": "Materialproben"},
  {"nr": "60.230", "name": "Materialprobe Lehm-Farbputz grob ROT (Art.Nr.: 10.230 )", "desc": "2 kg-Beutel", "ve": 1, "kat": "Materialproben"},
  {"nr": "60.240", "name": "Materialprobe Lehm-Farbputz grob GRÜN (Art.Nr.: 10.240 )", "desc": "2 kg-Beutel", "ve": 1, "kat": "Materialproben"},
  {"nr": "60.250", "name": "Materialprobe Lehm-Farbputz grob GELB (Art.Nr.: 10.250)", "desc": "2 kg-Beutel", "ve": 1, "kat": "Materialproben"},
  {"nr": "60.260", "name": "Materialprobe Lehm-Farbputz grob BEIGE (Art.Nr.: 10.260)", "desc": "2 kg-Beutel", "ve": 1, "kat": "Materialproben"},
  {"nr": "60.40.999.BTL", "name": "YOSIMA Materialprobe, Mischfarbe", "desc": "2 kg-Beutel, Farbe nach Wahl · BITTE GEWÜNSCHTEN FARBTON ANGEBEN!", "ve": 1, "kat": "Materialproben"},
  {"nr": "60.40.999.BTL.Z", "name": "YOSIMA Materialprobe, Produkt mit Strukturzuschlag", "desc": "2 kg-Beutel, Farbe und Strukturzuschlag nach Wahl · BITTE GEWÜNSCHTEN FARBTON UND STRUKTURZUSCHLAG ANGEBEN!", "ve": 1, "kat": "Materialproben"}
];
